default:
  outputs:
    dev:
    type: snowflake
    threads: 1
    account: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
    user: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
    role: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
    password: ${{ secrets.DBT_SNOWFLAKE_PW }}
    database: ${{ secrets.DBT_SNOWFLAKE_DATABASE }}
    warehouse: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
    schema: ${{ secrets.DBT_SNOWFLAKE_SCHEMA }}
    client_session_keep_alive: False
    query_tag: github_action_queries
