WITH user_data_clean AS (SELECT * FROM ACTIVEUSE.RAW.USER_DATA_RAW)
  SELECT
    OWNER_ID,
    OWNER_NAME,
    OWNER_EMAIL_ADDRESS,
    TRIM(SPLIT_PART(OWNER_ADDRESS, ',', 1)) AS OWNER_STREET,
    TRIM(SPLIT_PART(OWNER_ADDRESS, ',', 2)) AS OWNER_CITY,
    TRIM(SPLIT_PART(OWNER_ADDRESS, ',', 3)) AS OWNER_STATE,
    TRIM(SPLIT_PART(OWNER_ADDRESS, ',', 4)) AS OWNER_ZIPCODE,
    CREATED_AT,
    UPDATED_AT
  FROM
    user_data_clean