name: schedule_dbt_job

on:
schedule:
    # run at 5AM every single day
    - cron: "0 5 * * *"
push:
    branches:
    # run on push to master branch
    - master
env:
DBT_PROFILES_DIR: ./profile

DBT_SNOWFLAKE_USERNAME: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
DBT_SNOWFLAKE_PW: ${{ secrets.DBT_SNOWFLAKE_PW }}
DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}

jobs:
schedule_dbt_job:
    name: schedule_dbt_job
    runs-on: ubuntu-latest

    steps:
    - name: Check out
        uses: actions/checkout@master

    - uses: actions/setup-python@v2
        with:
        python-version: "3.11.x"

    - name: Install dependencies
        run: |
        pip install dbt
        dbt deps

    # dbt related commands here - run use --target prod/dev to run for specific environments
    - name: Run dbt models
        run: dbt run

    - name: Test dbt models
<<<<<<< HEAD
        run: dbt test
=======
        run: dbt test
>>>>>>> 079b756 (add requirements.txt)
